### ISSUE TITLE
Updated performance by ADRP

### ISSUE THREAD

**Issue by lee212** [radical-collaboration/DeepDriveMD#10]
The updated performance results:
- adrp: https://github.com/radical-experiments/deepdriveMD/blob/master/analysis/adrp-performance.ipynb
- fs-peptide: https://github.com/radical-experiments/deepdriveMD/blob/master/analysis/fspep-performance.ipynb

along with RADICAL-Cybertools:
- https://github.com/radical-experiments/deepdriveMD/blob/master/analysis/adrp_ovh.ipynb

**Comment by lee212** [comment]
Again, fyi @hengma1001 , @arvind

**Comment by arvind** [comment]
Hi, you are tagging the wrong Arvind :)

**Comment by shantenujha** [comment]
Yes, apologies @arvind 

We meant Arvind Ramanathan (Argonne Lab).

**Comment by lee212** [comment]
https://github.com/radical-experiments/deepdriveMD/blob/master/data/raw/new_model/ddm_ru.ipynb
- preliminary results with updated pipeline
- pytorch vae resne with amp and ddp
- adrp with 1 iteration
